tech = "sky130A"
grid = 0.05

[layers]

[layers.nwell]
desc = "define nwell for placing PMOS transistors"
width = 0.84
space = 1.27
area = 0.0

[layers.poly]
desc = "define transistor gates"
width = 0.15
space = 0.21
area = 0.0
extensions = [
  { layer = "ndiff", extend = 0.13 },
  { layer = "pdiff", extend = 0.13 },
]

[layers.ct]
desc = "contact between li and m1"
width = 0.17
space = 0.19
area = 0.0289

[layers.li]
desc = "local interconnect"
width = 0.17
space = 0.17
area = 0.0561

[layers.licon]
desc = "defines contacts between poly/diff/tap and local interconnect"
width = 0.17
space = 0.17
area = 0.0289
enclosures = [
  { layer = "ndiff", enclosure = 0.04, one_side = false },
  { layer = "pdiff", enclosure = 0.04, one_side = false },
  { layer = "ndiff", enclosure = 0.06, one_side = true },
  { layer = "pdiff", enclosure = 0.06, one_side = true },
  { layer = "poly", enclosure = 0.05, one_side = false },
  { layer = "poly", enclosure = 0.08, one_side = true },
]

[layers.m1]
desc = "first level of metal interconnects"
width = 0.14
space = 0.14
area = 0.083
enclosures = [
  { layer = "ct", enclosure = 0.03, one_side = true },
]
