name: Rust

on:
  push:
  pull_request:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Lint
        run: make lint
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Build and test
        run: make test
