name: Rust

on:
  push:
  pull_request:

jobs:
  check-workspace:
    name: Build, lint, and test
    runs-on: [self-hosted, linux, magic-8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        run: |
          echo "/usr/local/bin" >> $GITHUB_PATH
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Compile
        run: make check
      - name: Lint
        run: make lint
      - name: Build and test
        run: make test
